### ISSUE TITLE
[How to Instal]

### ISSUE THREAD

**Issue by XerozBoyz** [guneyct/gct-chat#2]
.

**Comment by XerozBoyz** [comment]
and how to place files correctly

**Comment by XerozBoyz** [comment]
![Screenshot (102)](https://github.com/user-attachments/assets/cda40b1a-8cae-4b82-83b3-172b38e5321d)

**Comment by XerozBoyz** [comment]
and how to place files correctly
![Screenshot (102)](https://github.com/user-attachments/assets/cda40b1a-8cae-4b82-83b3-172b38e5321d)
![Screenshot (103)](https://github.com/user-attachments/assets/eb433f3f-4dc7-4f0c-b656-c1f7746b3a14)
![Screenshot (104)](https://github.com/user-attachments/assets/798418e5-2c12-432f-9105-cfebccee7766)
then i press T and text and i cant press T ever

**Comment by guneyct** [comment]
> and how to place files correctly ![Screenshot (102)](https://private-user-images.githubusercontent.com/143891225/377639511-cda40b1a-8cae-4b82-83b3-172b38e5321d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDE1NDQsIm5iZiI6MTcyOTIwMTI0NCwicGF0aCI6Ii8xNDM4OTEyMjUvMzc3NjM5NTExLWNkYTQwYjFhLThjYWUtNGI4Mi04M2IzLTE3MmIzOGU1MzIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMTQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjJlNTQ0MzdiNDJjNjY3NjFlNmExODg1MjYzOWU5ZjA1MjdmYmEwMzYwOGQ2MGRlOTRjNDIyY2MzMDY3NzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T9elgKqaEov-_Q4xPb-462rK3K5ROyWWrEkKqNQsd9Q) ![Screenshot (103)](https://private-user-images.githubusercontent.com/143891225/377639902-eb433f3f-4dc7-4f0c-b656-c1f7746b3a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDE1NDQsIm5iZiI6MTcyOTIwMTI0NCwicGF0aCI6Ii8xNDM4OTEyMjUvMzc3NjM5OTAyLWViNDMzZjNmLTRkYzctNGYwYy1iNjU2LWMxZjc3NDZiM2ExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMTQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzkzM2RhYmFmODg1YzRiZmEzMTJhMWNiYWYzZTQ4MDBmNDczZDMyMzQ2NGJiZmU5Y2ZiY2UyNzZhMTJjNmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eWTU1kSduvynwzmUfjcXZlvF44IxM1jtdhYfQHL1v9o) ![Screenshot (104)](https://private-user-images.githubusercontent.com/143891225/377640106-798418e5-2c12-432f-9105-cfebccee7766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDE1NDQsIm5iZiI6MTcyOTIwMTI0NCwicGF0aCI6Ii8xNDM4OTEyMjUvMzc3NjQwMTA2LTc5ODQxOGU1LTJjMTItNDMyZi05MTA1LWNmZWJjY2VlNzc2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMTQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmY5YTQ4MjIxZmEzOTllOWQ3ZGUwYTQ3OWY4YzY1MzcyYjFkOTdjMjYxN2E1MTJjOTIwNmM4NWY3NWFkN2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ATdqHJw0qK6JTQHk4Ahzds6cy-AuBNZ2_5KCNfH8I2M) then i press T and text and i cant press T ever

You need tonuse the files in the zip folder. And dont change the names

**Comment by XerozBoyz** [comment]
> > and how to place files correctly ![Screenshot (102)](https://private-user-images.githubusercontent.com/143891225/377639511-cda40b1a-8cae-4b82-83b3-172b38e5321d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDE1NDQsIm5iZiI6MTcyOTIwMTI0NCwicGF0aCI6Ii8xNDM4OTEyMjUvMzc3NjM5NTExLWNkYTQwYjFhLThjYWUtNGI4Mi04M2IzLTE3MmIzOGU1MzIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMTQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjJlNTQ0MzdiNDJjNjY3NjFlNmExODg1MjYzOWU5ZjA1MjdmYmEwMzYwOGQ2MGRlOTRjNDIyY2MzMDY3NzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T9elgKqaEov-_Q4xPb-462rK3K5ROyWWrEkKqNQsd9Q) ![Screenshot (103)](https://private-user-images.githubusercontent.com/143891225/377639902-eb433f3f-4dc7-4f0c-b656-c1f7746b3a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDE1NDQsIm5iZiI6MTcyOTIwMTI0NCwicGF0aCI6Ii8xNDM4OTEyMjUvMzc3NjM5OTAyLWViNDMzZjNmLTRkYzctNGYwYy1iNjU2LWMxZjc3NDZiM2ExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMTQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzkzM2RhYmFmODg1YzRiZmEzMTJhMWNiYWYzZTQ4MDBmNDczZDMyMzQ2NGJiZmU5Y2ZiY2UyNzZhMTJjNmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eWTU1kSduvynwzmUfjcXZlvF44IxM1jtdhYfQHL1v9o) ![Screenshot (104)](https://private-user-images.githubusercontent.com/143891225/377640106-798418e5-2c12-432f-9105-cfebccee7766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDE1NDQsIm5iZiI6MTcyOTIwMTI0NCwicGF0aCI6Ii8xNDM4OTEyMjUvMzc3NjQwMTA2LTc5ODQxOGU1LTJjMTItNDMyZi05MTA1LWNmZWJjY2VlNzc2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMTQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmY5YTQ4MjIxZmEzOTllOWQ3ZGUwYTQ3OWY4YzY1MzcyYjFkOTdjMjYxN2E1MTJjOTIwNmM4NWY3NWFkN2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ATdqHJw0qK6JTQHk4Ahzds6cy-AuBNZ2_5KCNfH8I2M) then i press T and text and i cant press T ever
> 
i put your chat in [chat] and ensure chat but idk is dont work but how to install u can expain that plsss
![Screenshot (105)](https://github.com/user-attachments/assets/83cb6df1-da10-482f-b985-66d8fb57255b)

**Comment by guneyct** [comment]
Put them in the same folder and the start öder should be like this:

ensure chat
ensure chat-theme-gtao


If there is another chat script delete that chat script.

**Comment by XerozBoyz** [comment]
> Put them in the same folder and the start öder should be like this:
> 
> ensure chat ensure chat-theme-gtao
> 
> If there is another chat script delete that chat script.

I can’t delete chat bc it’s empty idk why but this only problem but how do u install like u

**Comment by guneyct** [comment]
I installed it like intold you. First they need to be in the same folder then the start order must be like this:

ensure chat
ensure chat-theme-gtao

**Comment by XerozBoyz** [comment]
![Screenshot (108)](https://github.com/user-attachments/assets/414149b3-237b-45f1-b3da-a6c5a84e7d25)
![Screenshot (106)](https://github.com/user-attachments/assets/7390f2fb-bd0a-429b-a7e2-9716b38a59e7)
i cant and delete default chat and chat theme then i get gta online chat

**Comment by guneyct** [comment]
Then only start the chat

**Comment by XerozBoyz** [comment]
![Screenshot (109)](https://github.com/user-attachments/assets/347d5c2c-4a8f-49f2-9306-8a591eca48ba)
how

**Comment by guneyct** [comment]
Whats the problem

**Comment by XerozBoyz** [comment]
> Whats the problem

on top-left i ensure your char then i can use it

**Comment by XerozBoyz** [comment]
![Screenshot (110)](https://github.com/user-attachments/assets/95efd5f5-b2a9-4598-9669-5a1eb918bcf4)
i got it guys just # add start chat system and start eneure gct-chat (chat) after qb-core
